version: '3.8'

services:
  postgres:
    image: postgres
    container_name: cuppa-local-postgresql
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - posgress-server.env
    networks:
      - cuppa-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
#      - ./data/postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo
    container_name: cuppa-local-mongo
    networks:
      - cuppa-network
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
#      - ./data/mongo-data:/data/db

  redis:
    image: redis
    container_name: cuppa-local-redis
    networks:
      - cuppa-network
    expose:
      - 6379
    ports:
      - 6379:6379

  adminer:
    image: adminer
    container_name: cuppa-local-adminer
    restart: always
    networks:
      - cuppa-network
    ports:
      - 18080:8080

networks:
  cuppa-network:
    external:
      name: "cuppa-network"

volumes:
  postgres-data:
    external:
      name: "postgres-data"
  mongo-data:
    external:
      name: "mongo-data"

