version: '3.2'

services:
  cuppa-auth:
    image: cuppa-auth:latest
    container_name: fin-cuppa-auth
    environment:
      - FASTIFY_PORT=3030
      - POSTGRESQL_CONNECTION_STRING=postgres://cuppa:toor@postgres/cuppa-authentication
    networks:
      - cuppa-network
    expose:
      - 3030
    ports:
      - 3030:3030

networks:
  cuppa-network:
    external:
      name: "cuppa-network"
