apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: us
      containers:
        - name: cuppa-web
          image: cuppa/web:v5
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3500
              name: web
              protocol: TCP
          readinessProbe:
            httpGet:
              port: web
              path: /status
          envFrom:
            - configMapRef:
                name: cuppa-web-config
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cuppa-web
  labels:
    app: web
spec:
  type: NodePort
  ports:
    - port: 3500
      nodePort: 32500
  selector:
    app: web
