apiVersion: v1
kind: ConfigMap
metadata:
  name: cuppa-auth-config
  labels:
    app: auth
data:
  PORT: "3030"
  FASTIFY_ADDRESS: "0.0.0.0"
  POSTGRESQL_CONNECTION_STRING: "postgres://cuppa:password@postgres/cuppa-authentication"
