apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: cuppa-auth
          image: cuppa/auth:v3
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3030
          envFrom:
            - configMapRef:
                name: cuppa-auth-config
---
apiVersion: v1
kind: Service
metadata:
  name: cuppa-auth
  labels:
    app: auth
spec:
  type: NodePort
  ports:
    - port: 3030
      nodePort: 32030
  selector:
    app: auth
