apiVersion: v1
kind: Secret
metadata:
  name: finance-stats-secret
  namespace: cuppa
  labels:
    app: finance-stats
type: Opaque
data:
  POSTGRESQL_CONNECTION_STRING: cG9zdGdyZXM6Ly9jdXBwYTp0b29yQHBvc3RncmVzLXBvc3RncmVzcWwuZGVmYXVsdC9jdXBwYS1maW5hbmNlLXN0YXRzCg==
  REDIS_CONNECTION_STRING: cmVkaXM6Ly86OHlOQWM2eFpqQUByZWRpcy1tYXN0ZXIuZGVmYXVsdDo2Mzc5Cg==
